#!/bin/bash
#
# This is an example init.d script for starting servepage service
#

PROGDIR=$HOME/bin
PROGNAME=servepages
PROGPATH=$PROGDIR/$PROGNAME
LOGDIR=/Sites/archives.caltech.edu/logs
LOGPATH=$LOGDIR/$PROGNAME.log
CONFIG=/etc/cait.bash

# Read in local configuration
. $CONFIG

function consolelog {
    echo $(date +"%Y/%m/%d %H:%M:%S")" $@"
}

# Set place for log
mkdir -p $LOGDIR
touch $LOGPATH

function startService() {
    $PROGPATH &>> $LOGPATH &
    PID="$!"
    echo "$PID" >> /var/run/$PROGNAME.pid
    consolelog "Started $PROGNAME $PID"
    echo "Started $PROGNAME $PID" >> $LOGPATH
    echo "Using templates $CAIT_TEMPLATES">> $LOGPATH
}

function stopService() {
    cat /var/run/$PROGNAME.pid | while read PID; do
	    if [ "$PID" != "" ]; then
            consolelog "Stopping $PROGNAME $PID"
    	    echo "Stopping $PROGNAME $PID" >> $LOGPATH
            kill $PID
        fi
        sleep 3
    done
    /bin/rm /var/run/$PROGNAME.pid
}

# Handle requested action
case "$1" in
  start)
    startService
    ;;
  stop)
    stopService
    ;;
  restart)
     stopService
     startService
     ;;
  status)
    if [ -f /var/run/$PROGNAME.pid ]; then
        consolelog "$PROGNAME running as $(cat /var/run/$PROGNAME.pid)"
    else
        consolelog "$PROGNAME not running"
    fi
    ;;
  *)
    echo 'usage: '$PROGNAME' [start|stop|restart|status]'
esac
